// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/99designs/gqlgen/graphql"
)

type UpdateUser struct {
	DisplayName  string          `json:"displayName"`
	RealName     string          `json:"realName"`
	CustomURL    string          `json:"customUrl"`
	Summary      string          `json:"summary"`
	CountryID    int64           `json:"countryId"`
	Avatar       *graphql.Upload `json:"avatar"`
	ProfileTheme string          `json:"profileTheme"`
}
