// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/99designs/gqlgen/graphql"
)

type CreateGame struct {
	Title              string            `json:"title"`
	Description        string            `json:"description"`
	Price              float64           `json:"price"`
	Banner             graphql.Upload    `json:"banner"`
	Slideshows         []*graphql.Upload `json:"slideshows"`
	GameTags           []int64           `json:"gameTags"`
	SystemRequirements string            `json:"systemRequirements"`
}

type GamePagination struct {
	Data       []*Game `json:"data"`
	TotalPages int     `json:"totalPages"`
}

type PromoPagination struct {
	Data       []*Promo `json:"data"`
	TotalPages int      `json:"totalPages"`
}

type UpdateGame struct {
	ID                 int64             `json:"id"`
	Title              string            `json:"title"`
	Description        string            `json:"description"`
	Price              float64           `json:"price"`
	Banner             *graphql.Upload   `json:"banner"`
	Slideshows         []*graphql.Upload `json:"slideshows"`
	GameTags           []int64           `json:"gameTags"`
	SystemRequirements string            `json:"systemRequirements"`
}

type UpdateUser struct {
	DisplayName  string          `json:"displayName"`
	RealName     string          `json:"realName"`
	CustomURL    string          `json:"customUrl"`
	Summary      string          `json:"summary"`
	CountryID    int64           `json:"countryId"`
	Avatar       *graphql.Upload `json:"avatar"`
	ProfileTheme string          `json:"profileTheme"`
}

type UserPagination struct {
	Data       []*User `json:"data"`
	TotalPages int     `json:"totalPages"`
}
